import type { Tool } from '@/types'

export const TOOLS: Tool[] = [
  // テキストツール (20)
  {
    id: 'text-counter',
    name: 'Character Counter',
    nameJa: '文字数カウンター',
    description: 'Count characters, words, and bytes in real-time',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['text', 'counter', 'characters', 'words'],
    icon: 'Type',
    isActive: true,
    order: 1,
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    nameJa: 'ケース変換',
    description: 'Convert text case: uppercase, lowercase, camelCase, snake_case, etc.',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['text', 'case', 'convert', 'camelCase', 'snake_case'],
    icon: 'CaseSensitive',
    isActive: true,
    order: 2,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    nameJa: 'Base64エンコーダー',
    description: 'Encode and decode Base64 strings',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['text', 'base64', 'encode', 'decode'],
    icon: 'Binary',
    isActive: true,
    order: 3,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    nameJa: 'URLエンコーダー',
    description: 'Encode and decode URL strings',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['text', 'url', 'encode', 'decode'],
    icon: 'Link',
    isActive: true,
    order: 4,
  },
  {
    id: 'html-entities',
    name: 'HTML Entity Converter',
    nameJa: 'HTMLエンティティ変換',
    description: 'Convert HTML entities',
    category: 'text',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['html', 'entities', 'convert'],
    icon: 'Code2',
    isActive: true,
    order: 5,
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    nameJa: 'テキスト差分',
    description: 'Compare two texts and show differences',
    category: 'text',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['text', 'diff', 'compare'],
    icon: 'FileSearch',
    isActive: true,
    order: 6,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    nameJa: '正規表現テスター',
    description: 'Test regular expressions',
    category: 'text',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['regex', 'test', 'pattern'],
    icon: 'Regex',
    isActive: true,
    order: 7,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    nameJa: 'JSON整形',
    description: 'Format, minify, and validate JSON',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['json', 'format', 'validate'],
    icon: 'Braces',
    isActive: true,
    order: 8,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    nameJa: 'XML整形',
    description: 'Format and validate XML',
    category: 'text',
    difficulty: 'medium',
    priority: 'low',
    tags: ['xml', 'format', 'validate'],
    icon: 'FileCode',
    isActive: true,
    order: 9,
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    nameJa: 'Markdownプレビュー',
    description: 'Preview Markdown as HTML',
    category: 'text',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['markdown', 'preview', 'html'],
    icon: 'FileText',
    isActive: true,
    order: 10,
  },
  {
    id: 'text-encrypt',
    name: 'Text Encryption',
    nameJa: 'テキスト暗号化',
    description: 'Encrypt and decrypt text with AES',
    category: 'text',
    difficulty: 'medium',
    priority: 'low',
    tags: ['encrypt', 'decrypt', 'aes', 'security'],
    icon: 'Lock',
    isActive: true,
    order: 11,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    nameJa: 'パスワード生成',
    description: 'Generate secure random passwords',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['password', 'generate', 'security'],
    icon: 'Key',
    isActive: true,
    order: 12,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    nameJa: 'Lorem Ipsum生成',
    description: 'Generate placeholder text',
    category: 'text',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['lorem', 'ipsum', 'placeholder', 'dummy'],
    icon: 'Text',
    isActive: true,
    order: 13,
  },
  {
    id: 'text-sort',
    name: 'Text Sort',
    nameJa: 'テキストソート',
    description: 'Sort lines of text',
    category: 'text',
    difficulty: 'easy',
    priority: 'low',
    tags: ['text', 'sort', 'lines'],
    icon: 'ArrowUpDown',
    isActive: true,
    order: 14,
  },
  {
    id: 'remove-duplicates',
    name: 'Remove Duplicate Lines',
    nameJa: '重複行削除',
    description: 'Remove duplicate lines from text',
    category: 'text',
    difficulty: 'easy',
    priority: 'low',
    tags: ['text', 'duplicate', 'remove'],
    icon: 'Minimize2',
    isActive: true,
    order: 15,
  },
  {
    id: 'add-line-numbers',
    name: 'Add Line Numbers',
    nameJa: '行番号追加',
    description: 'Add line numbers to text',
    category: 'text',
    difficulty: 'easy',
    priority: 'low',
    tags: ['text', 'line', 'numbers'],
    icon: 'Hash',
    isActive: true,
    order: 16,
  },
  {
    id: 'text-reverse',
    name: 'Reverse Text',
    nameJa: 'テキストリバース',
    description: 'Reverse text characters',
    category: 'text',
    difficulty: 'easy',
    priority: 'low',
    tags: ['text', 'reverse'],
    icon: 'Repeat',
    isActive: true,
    order: 17,
  },
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    nameJa: '空白削除',
    description: 'Remove extra spaces, tabs, and line breaks',
    category: 'text',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['text', 'whitespace', 'remove'],
    icon: 'Space',
    isActive: true,
    order: 18,
  },
  {
    id: 'fullwidth-halfwidth',
    name: 'Full/Half Width Converter',
    nameJa: '全角半角変換',
    description: 'Convert between full-width and half-width characters',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['japanese', 'fullwidth', 'halfwidth', 'convert'],
    icon: 'Languages',
    isActive: true,
    order: 19,
  },
  {
    id: 'hiragana-katakana',
    name: 'Hiragana/Katakana Converter',
    nameJa: 'ひらがな/カタカナ変換',
    description: 'Convert between hiragana and katakana',
    category: 'text',
    difficulty: 'easy',
    priority: 'high',
    tags: ['japanese', 'hiragana', 'katakana', 'convert'],
    icon: 'Languages',
    isActive: true,
    order: 20,
  },

  // 画像ツール (15)
  {
    id: 'image-converter',
    name: 'Image Format Converter',
    nameJa: '画像形式変換',
    description: 'Convert images between JPG, PNG, WebP formats',
    category: 'image',
    difficulty: 'medium',
    priority: 'high',
    tags: ['image', 'convert', 'jpg', 'png', 'webp'],
    icon: 'Image',
    isActive: true,
    order: 21,
  },
  {
    id: 'image-resize',
    name: 'Image Resizer',
    nameJa: '画像リサイズ',
    description: 'Resize images to specified dimensions',
    category: 'image',
    difficulty: 'medium',
    priority: 'high',
    tags: ['image', 'resize', 'scale'],
    icon: 'Maximize2',
    isActive: true,
    order: 22,
  },
  {
    id: 'image-compress',
    name: 'Image Compressor',
    nameJa: '画像圧縮',
    description: 'Compress images while maintaining quality',
    category: 'image',
    difficulty: 'medium',
    priority: 'high',
    tags: ['image', 'compress', 'optimize'],
    icon: 'Minimize',
    isActive: true,
    order: 23,
  },
  {
    id: 'image-crop',
    name: 'Image Cropper',
    nameJa: '画像トリミング',
    description: 'Crop images to desired area',
    category: 'image',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['image', 'crop', 'trim'],
    icon: 'Crop',
    isActive: true,
    order: 24,
  },
  {
    id: 'image-rotate',
    name: 'Image Rotator',
    nameJa: '画像回転・反転',
    description: 'Rotate and flip images',
    category: 'image',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['image', 'rotate', 'flip'],
    icon: 'RotateCw',
    isActive: true,
    order: 25,
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    nameJa: 'QRコード生成',
    description: 'Generate QR codes from text or URLs',
    category: 'image',
    difficulty: 'easy',
    priority: 'high',
    tags: ['qr', 'code', 'generate'],
    icon: 'QrCode',
    isActive: true,
    order: 26,
  },
  {
    id: 'qr-reader',
    name: 'QR Code Reader',
    nameJa: 'QRコードスキャン',
    description: 'Read QR codes from images',
    category: 'image',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['qr', 'code', 'scan', 'read'],
    icon: 'ScanLine',
    isActive: true,
    order: 27,
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    nameJa: 'カラーピッカー',
    description: 'Pick colors from images',
    category: 'image',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['color', 'picker', 'image'],
    icon: 'Pipette',
    isActive: true,
    order: 28,
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    nameJa: 'グラデーション生成',
    description: 'Generate CSS gradients',
    category: 'image',
    difficulty: 'easy',
    priority: 'low',
    tags: ['gradient', 'css', 'color'],
    icon: 'Palette',
    isActive: true,
    order: 29,
  },
  {
    id: 'icon-generator',
    name: 'Icon Generator',
    nameJa: 'アイコン生成',
    description: 'Generate simple icons from text',
    category: 'image',
    difficulty: 'medium',
    priority: 'low',
    tags: ['icon', 'generate', 'text'],
    icon: 'Sparkles',
    isActive: true,
    order: 30,
  },
  {
    id: 'image-filter',
    name: 'Image Filter',
    nameJa: '画像フィルター',
    description: 'Apply filters to images',
    category: 'image',
    difficulty: 'medium',
    priority: 'low',
    tags: ['image', 'filter', 'effect'],
    icon: 'Wand2',
    isActive: true,
    order: 31,
  },
  {
    id: 'base64-image',
    name: 'Base64 Image Converter',
    nameJa: 'Base64画像変換',
    description: 'Convert images to/from Base64',
    category: 'image',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['image', 'base64', 'convert'],
    icon: 'FileImage',
    isActive: true,
    order: 32,
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    nameJa: '画像メタデータ',
    description: 'View EXIF and other metadata',
    category: 'image',
    difficulty: 'medium',
    priority: 'low',
    tags: ['image', 'metadata', 'exif'],
    icon: 'Info',
    isActive: true,
    order: 33,
  },
  {
    id: 'placeholder-generator',
    name: 'Placeholder Image Generator',
    nameJa: 'プレースホルダー生成',
    description: 'Generate placeholder images',
    category: 'image',
    difficulty: 'easy',
    priority: 'low',
    tags: ['placeholder', 'image', 'dummy'],
    icon: 'ImagePlus',
    isActive: true,
    order: 34,
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    nameJa: 'Favicon生成',
    description: 'Generate favicons from images',
    category: 'image',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['favicon', 'icon', 'generate'],
    icon: 'Star',
    isActive: true,
    order: 35,
  },

  // 開発者ツール (20)
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    nameJa: 'JSON→YAML',
    description: 'Convert JSON to YAML format',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['json', 'yaml', 'convert'],
    icon: 'FileJson',
    isActive: true,
    order: 36,
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    nameJa: 'YAML→JSON',
    description: 'Convert YAML to JSON format',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['yaml', 'json', 'convert'],
    icon: 'FileCode2',
    isActive: true,
    order: 37,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    nameJa: 'SQL整形',
    description: 'Format SQL queries',
    category: 'dev',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['sql', 'format', 'query'],
    icon: 'Database',
    isActive: true,
    order: 38,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    nameJa: 'JWTデコーダー',
    description: 'Decode and inspect JWT tokens',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['jwt', 'decode', 'token'],
    icon: 'ShieldCheck',
    isActive: true,
    order: 39,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    nameJa: 'ハッシュ生成',
    description: 'Generate MD5, SHA1, SHA256 hashes',
    category: 'dev',
    difficulty: 'easy',
    priority: 'high',
    tags: ['hash', 'md5', 'sha256', 'crypto'],
    icon: 'Hash',
    isActive: true,
    order: 40,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    nameJa: 'UUID生成',
    description: 'Generate UUID v4',
    category: 'dev',
    difficulty: 'easy',
    priority: 'high',
    tags: ['uuid', 'guid', 'generate'],
    icon: 'Fingerprint',
    isActive: true,
    order: 41,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    nameJa: 'Timestamp変換',
    description: 'Convert Unix timestamps to dates',
    category: 'dev',
    difficulty: 'easy',
    priority: 'high',
    tags: ['timestamp', 'unix', 'date', 'convert'],
    icon: 'Clock',
    isActive: true,
    order: 42,
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    nameJa: 'Cron式生成',
    description: 'Build cron expressions',
    category: 'dev',
    difficulty: 'medium',
    priority: 'low',
    tags: ['cron', 'schedule', 'expression'],
    icon: 'Calendar',
    isActive: true,
    order: 43,
  },
  {
    id: 'color-code-converter',
    name: 'Color Code Converter',
    nameJa: 'カラーコード変換',
    description: 'Convert between HEX, RGB, HSL',
    category: 'dev',
    difficulty: 'easy',
    priority: 'high',
    tags: ['color', 'hex', 'rgb', 'hsl'],
    icon: 'Palette',
    isActive: true,
    order: 44,
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    nameJa: 'CSS整形',
    description: 'Format and minify CSS',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['css', 'format', 'minify'],
    icon: 'FileCode',
    isActive: true,
    order: 45,
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    nameJa: 'JavaScript整形',
    description: 'Format and minify JavaScript',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['javascript', 'format', 'minify'],
    icon: 'FileCode',
    isActive: true,
    order: 46,
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    nameJa: 'HTML整形',
    description: 'Format and minify HTML',
    category: 'dev',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['html', 'format', 'minify'],
    icon: 'FileCode',
    isActive: true,
    order: 47,
  },
  {
    id: 'code-diff',
    name: 'Code Diff',
    nameJa: 'コード差分',
    description: 'Compare code and show differences',
    category: 'dev',
    difficulty: 'medium',
    priority: 'low',
    tags: ['code', 'diff', 'compare'],
    icon: 'GitCompare',
    isActive: true,
    order: 48,
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    nameJa: 'User Agentパーサー',
    description: 'Parse User Agent strings',
    category: 'dev',
    difficulty: 'easy',
    priority: 'low',
    tags: ['user-agent', 'parse', 'browser'],
    icon: 'Globe',
    isActive: true,
    order: 49,
  },
  {
    id: 'ip-info',
    name: 'IP Address Info',
    nameJa: 'IP情報',
    description: 'Show IP address information',
    category: 'dev',
    difficulty: 'easy',
    priority: 'low',
    tags: ['ip', 'address', 'info'],
    icon: 'Network',
    isActive: true,
    order: 50,
  },

  // 計算・変換ツール (20)
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    nameJa: '単位変換',
    description: 'Convert length, weight, temperature',
    category: 'calc',
    difficulty: 'easy',
    priority: 'high',
    tags: ['unit', 'convert', 'length', 'weight'],
    icon: 'Ruler',
    isActive: true,
    order: 51,
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    nameJa: '通貨換算',
    description: 'Convert between currencies',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['currency', 'money', 'convert'],
    icon: 'DollarSign',
    isActive: true,
    order: 52,
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    nameJa: 'パーセント計算',
    description: 'Calculate percentages',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['percentage', 'calculate'],
    icon: 'Percent',
    isActive: true,
    order: 53,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    nameJa: 'BMI計算',
    description: 'Calculate Body Mass Index',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['bmi', 'health', 'calculate'],
    icon: 'Heart',
    isActive: true,
    order: 54,
  },
  {
    id: 'loan-calculator',
    name: 'Loan Calculator',
    nameJa: 'ローン計算',
    description: 'Calculate loan payments',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['loan', 'mortgage', 'calculate'],
    icon: 'Home',
    isActive: true,
    order: 55,
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    nameJa: '年齢計算',
    description: 'Calculate age from birthdate',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['age', 'birthday', 'calculate'],
    icon: 'Cake',
    isActive: true,
    order: 56,
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    nameJa: '日数計算',
    description: 'Calculate days between dates',
    category: 'calc',
    difficulty: 'easy',
    priority: 'high',
    tags: ['date', 'days', 'calculate'],
    icon: 'Calendar',
    isActive: true,
    order: 57,
  },
  {
    id: 'time-calculator',
    name: 'Time Calculator',
    nameJa: '時間計算',
    description: 'Add and subtract time',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['time', 'calculate', 'duration'],
    icon: 'Clock',
    isActive: true,
    order: 58,
  },
  {
    id: 'discount-calculator',
    name: 'Discount Calculator',
    nameJa: '割引計算',
    description: 'Calculate discounted prices',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['discount', 'price', 'calculate'],
    icon: 'Tag',
    isActive: true,
    order: 59,
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    nameJa: 'チップ計算',
    description: 'Calculate tip amounts',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['tip', 'restaurant', 'calculate'],
    icon: 'Utensils',
    isActive: true,
    order: 60,
  },
  {
    id: 'fuel-calculator',
    name: 'Fuel Efficiency Calculator',
    nameJa: '燃費計算',
    description: 'Calculate fuel efficiency',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['fuel', 'car', 'calculate'],
    icon: 'Fuel',
    isActive: true,
    order: 61,
  },
  {
    id: 'byte-converter',
    name: 'Byte Converter',
    nameJa: 'バイト変換',
    description: 'Convert KB, MB, GB, TB',
    category: 'calc',
    difficulty: 'easy',
    priority: 'high',
    tags: ['byte', 'kb', 'mb', 'gb', 'convert'],
    icon: 'HardDrive',
    isActive: true,
    order: 62,
  },
  {
    id: 'speed-converter',
    name: 'Speed Converter',
    nameJa: 'スピード変換',
    description: 'Convert km/h, m/s, mph',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['speed', 'convert', 'kmh', 'mph'],
    icon: 'Gauge',
    isActive: true,
    order: 63,
  },
  {
    id: 'area-calculator',
    name: 'Area Calculator',
    nameJa: '面積計算',
    description: 'Calculate area of shapes',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['area', 'calculate', 'geometry'],
    icon: 'Square',
    isActive: true,
    order: 64,
  },
  {
    id: 'volume-calculator',
    name: 'Volume Calculator',
    nameJa: '体積計算',
    description: 'Calculate volume of shapes',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['volume', 'calculate', 'geometry'],
    icon: 'Box',
    isActive: true,
    order: 65,
  },
  {
    id: 'calorie-calculator',
    name: 'Calorie Calculator',
    nameJa: 'カロリー計算',
    description: 'Calculate calories burned',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['calorie', 'fitness', 'calculate'],
    icon: 'Activity',
    isActive: true,
    order: 66,
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest Calculator',
    nameJa: '複利計算',
    description: 'Calculate compound interest',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['compound', 'interest', 'investment'],
    icon: 'TrendingUp',
    isActive: true,
    order: 67,
  },
  {
    id: 'tax-calculator',
    name: 'Tax Calculator',
    nameJa: '税金計算',
    description: 'Calculate consumption tax',
    category: 'calc',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['tax', 'calculate', 'japan'],
    icon: 'Receipt',
    isActive: true,
    order: 68,
  },
  {
    id: 'fraction-calculator',
    name: 'Fraction Calculator',
    nameJa: '分数計算',
    description: 'Calculate with fractions',
    category: 'calc',
    difficulty: 'medium',
    priority: 'low',
    tags: ['fraction', 'calculate', 'math'],
    icon: 'Divide',
    isActive: true,
    order: 69,
  },
  {
    id: 'percentage-change',
    name: 'Percentage Change Calculator',
    nameJa: 'パーセント変化計算',
    description: 'Calculate percentage change',
    category: 'calc',
    difficulty: 'easy',
    priority: 'low',
    tags: ['percentage', 'change', 'calculate'],
    icon: 'TrendingUp',
    isActive: true,
    order: 70,
  },

  // PDFツール (10)
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    nameJa: '画像→PDF',
    description: 'Convert images to PDF',
    category: 'pdf',
    difficulty: 'medium',
    priority: 'high',
    tags: ['pdf', 'image', 'convert'],
    icon: 'FileImage',
    isActive: true,
    order: 71,
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    nameJa: 'PDF結合',
    description: 'Merge multiple PDFs',
    category: 'pdf',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['pdf', 'merge', 'combine'],
    icon: 'Combine',
    isActive: true,
    order: 72,
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    nameJa: 'PDF分割',
    description: 'Split PDF into pages',
    category: 'pdf',
    difficulty: 'medium',
    priority: 'medium',
    tags: ['pdf', 'split', 'separate'],
    icon: 'Scissors',
    isActive: true,
    order: 73,
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Rotate',
    nameJa: 'PDFページ回転',
    description: 'Rotate PDF pages',
    category: 'pdf',
    difficulty: 'medium',
    priority: 'low',
    tags: ['pdf', 'rotate'],
    icon: 'RotateCw',
    isActive: true,
    order: 74,
  },

  // SEO・マーケティングツール (10)
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    nameJa: 'メタタグ生成',
    description: 'Generate meta tags for SEO',
    category: 'seo',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['seo', 'meta', 'tags', 'ogp'],
    icon: 'Tags',
    isActive: true,
    order: 75,
  },
  {
    id: 'ogp-preview',
    name: 'OGP Preview',
    nameJa: 'OGPプレビュー',
    description: 'Preview OGP images and tags',
    category: 'seo',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['ogp', 'preview', 'social'],
    icon: 'Eye',
    isActive: true,
    order: 76,
  },
  {
    id: 'keyword-density',
    name: 'Keyword Density Checker',
    nameJa: 'キーワード密度',
    description: 'Check keyword density in text',
    category: 'seo',
    difficulty: 'easy',
    priority: 'low',
    tags: ['seo', 'keyword', 'density'],
    icon: 'Search',
    isActive: true,
    order: 77,
  },
  {
    id: 'slugify',
    name: 'URL Slug Generator',
    nameJa: 'URLスラッグ生成',
    description: 'Generate URL-friendly slugs',
    category: 'seo',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['url', 'slug', 'seo'],
    icon: 'Link',
    isActive: true,
    order: 78,
  },
  {
    id: 'robots-txt',
    name: 'Robots.txt Generator',
    nameJa: 'robots.txt生成',
    description: 'Generate robots.txt file',
    category: 'seo',
    difficulty: 'easy',
    priority: 'low',
    tags: ['robots', 'seo', 'txt'],
    icon: 'FileText',
    isActive: true,
    order: 79,
  },
  {
    id: 'utm-builder',
    name: 'UTM Parameter Builder',
    nameJa: 'UTMビルダー',
    description: 'Build UTM tracking parameters',
    category: 'seo',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['utm', 'tracking', 'analytics'],
    icon: 'BarChart',
    isActive: true,
    order: 80,
  },

  // ユーティリティ (20)
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    nameJa: 'ストップウォッチ',
    description: 'Simple stopwatch',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['time', 'stopwatch', 'timer'],
    icon: 'Timer',
    isActive: true,
    order: 81,
  },
  {
    id: 'timer',
    name: 'Timer',
    nameJa: 'タイマー',
    description: 'Countdown timer',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['time', 'timer', 'countdown'],
    icon: 'AlarmClock',
    isActive: true,
    order: 82,
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Timer',
    nameJa: 'ポモドーロタイマー',
    description: 'Pomodoro technique timer',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['pomodoro', 'timer', 'productivity'],
    icon: 'Tomato',
    isActive: true,
    order: 83,
  },
  {
    id: 'random-number',
    name: 'Random Number Generator',
    nameJa: 'ランダム数字生成',
    description: 'Generate random numbers',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['random', 'number', 'generate'],
    icon: 'Dices',
    isActive: true,
    order: 84,
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    nameJa: 'ランダム文字列生成',
    description: 'Generate random strings',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['random', 'string', 'generate'],
    icon: 'Shuffle',
    isActive: true,
    order: 85,
  },
  {
    id: 'dice-roller',
    name: 'Dice Roller',
    nameJa: 'サイコロ',
    description: 'Roll virtual dice',
    category: 'utility',
    difficulty: 'easy',
    priority: 'low',
    tags: ['dice', 'random', 'game'],
    icon: 'Dice3',
    isActive: true,
    order: 86,
  },
  {
    id: 'coin-flip',
    name: 'Coin Flip',
    nameJa: 'コイン投げ',
    description: 'Flip a virtual coin',
    category: 'utility',
    difficulty: 'easy',
    priority: 'low',
    tags: ['coin', 'random', 'flip'],
    icon: 'Coins',
    isActive: true,
    order: 87,
  },
  {
    id: 'lottery',
    name: 'Lottery Picker',
    nameJa: 'くじ引き',
    description: 'Random lottery picker',
    category: 'utility',
    difficulty: 'easy',
    priority: 'low',
    tags: ['lottery', 'random', 'picker'],
    icon: 'Gift',
    isActive: true,
    order: 88,
  },
  {
    id: 'bingo-card',
    name: 'Bingo Card Generator',
    nameJa: 'ビンゴカード生成',
    description: 'Generate bingo cards',
    category: 'utility',
    difficulty: 'easy',
    priority: 'low',
    tags: ['bingo', 'card', 'generate'],
    icon: 'Grid3x3',
    isActive: true,
    order: 89,
  },
  {
    id: 'team-maker',
    name: 'Team Maker',
    nameJa: 'チーム分け',
    description: 'Divide people into teams',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['team', 'group', 'divide'],
    icon: 'Users',
    isActive: true,
    order: 90,
  },
  {
    id: 'name-picker',
    name: 'Name Picker',
    nameJa: '名前ランダマイザー',
    description: 'Pick random names',
    category: 'utility',
    difficulty: 'easy',
    priority: 'low',
    tags: ['name', 'random', 'picker'],
    icon: 'UserCheck',
    isActive: true,
    order: 91,
  },
  {
    id: 'japan-holidays',
    name: 'Japanese Holiday Calendar',
    nameJa: '日本の祝日カレンダー',
    description: 'Show Japanese national holidays',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['calendar', 'holiday', 'japan'],
    icon: 'Calendar',
    isActive: true,
    order: 92,
  },
  {
    id: 'world-clock',
    name: 'World Clock',
    nameJa: '世界時計',
    description: 'Show time in different timezones',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['clock', 'world', 'timezone'],
    icon: 'Globe',
    isActive: true,
    order: 93,
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    nameJa: 'タイムゾーン変換',
    description: 'Convert between timezones',
    category: 'utility',
    difficulty: 'easy',
    priority: 'medium',
    tags: ['timezone', 'convert', 'time'],
    icon: 'MapPin',
    isActive: true,
    order: 94,
  },
]

// ツールをIDで検索する関数
export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === id)
}

// カテゴリ別にツールを取得する関数
export function getToolsByCategory(category: string): Tool[] {
  return TOOLS.filter((tool) => tool.category === category && tool.isActive)
}

// 検索機能
export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase()
  return TOOLS.filter(
    (tool) =>
      tool.isActive &&
      (tool.name.toLowerCase().includes(lowerQuery) ||
        tool.nameJa.toLowerCase().includes(lowerQuery) ||
        tool.description.toLowerCase().includes(lowerQuery) ||
        tool.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)))
  )
}

// 優先度の高いツールを取得
export function getHighPriorityTools(): Tool[] {
  return TOOLS.filter((tool) => tool.isActive && tool.priority === 'high')
}
